apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express

spec:
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: "admin"

          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: "admin"

          - name: ME_CONFIG_MONGODB_SERVER
            value: "mongo-service"

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30001

