apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  # key: value
  # server.conf |
  #   ------- data ---------
  #
  #   ------- data ---------
  # ca-cert.pem |
  #   file